import requests

from app.config import settings


def build_pr_title(ticket_id: str, dag_id: str) -> str:
    return f"[{ticket_id}] Add DAG {dag_id}"


def build_pr_body(
    ticket_id: str,
    dag_id: str,
    source: str,
    target: str,
    schedule: str,
    validation: dict,
) -> str:
    validation_status = validation.get("overall_status", "UNKNOWN")
    errors = validation.get("errors", [])
    warnings = validation.get("warnings", [])

    errors_text = "\n".join([f"- {error}" for error in errors]) if errors else "- None"
    warnings_text = "\n".join([f"- {warning}" for warning in warnings]) if warnings else "- None"

    return f"""
## Jira Ticket

{ticket_id}

## Change Summary

This PR adds a generated Airflow DAG.

## DAG Details

| Field | Value |
|---|---|
| DAG ID | `{dag_id}` |
| Source | `{source}` |
| Target | `{target}` |
| Schedule | `{schedule}` |

## Validation Result

Overall status: `{validation_status}`

### Errors

{errors_text}

### Warnings

{warnings_text}

## Human Review Checklist

Please verify:

- [ ] DAG name is correct
- [ ] Source path/system is correct
- [ ] Target table/system is correct
- [ ] Schedule is correct
- [ ] Retry policy is acceptable
- [ ] No secrets are hardcoded
- [ ] DAG follows team standards
- [ ] Generated test file is meaningful

## Safety Note

This PR was generated by the AI DAG Ops Assistant. Human review is required before merge.
""".strip()


def create_pull_request(
    ticket_id: str,
    dag_id: str,
    source: str,
    target: str,
    schedule: str,
    branch_name: str,
    validation: dict,
) -> dict:
    if not settings.github_token:
        return {
            "success": False,
            "message": "Missing GITHUB_TOKEN in .env",
        }

    if not settings.github_owner or not settings.github_repo:
        return {
            "success": False,
            "message": "Missing GITHUB_OWNER or GITHUB_REPO in .env",
        }

    url = f"https://api.github.com/repos/{settings.github_owner}/{settings.github_repo}/pulls"

    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    payload = {
        "title": build_pr_title(ticket_id, dag_id),
        "head": branch_name,
        "base": settings.github_base_branch,
        "body": build_pr_body(
            ticket_id=ticket_id,
            dag_id=dag_id,
            source=source,
            target=target,
            schedule=schedule,
            validation=validation,
        ),
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code in [200, 201]:
        data = response.json()
        return {
            "success": True,
            "pr_number": data.get("number"),
            "pr_url": data.get("html_url"),
            "title": data.get("title"),
        }

    return {
        "success": False,
        "status_code": response.status_code,
        "message": response.text,
    }