import requests

from app.config import settings


_OPERATION_TITLES = {
    "MODIFY_DAG": "Modify DAG",
    "DISABLE_DAG": "Disable DAG",
    "DEPRECATE_DAG": "Deprecate DAG",
    "ARCHIVE_DAG": "Archive DAG",
    "AI_GENERATED": "Add DAG",
    "CREATE_DAG": "Add DAG",
}


def build_pr_title(ticket_id: str, dag_id: str, operation: str = "CREATE_DAG", ai_generated: bool = False) -> str:
    prefix = "[AI-GEN]" if ai_generated else ""
    verb = _OPERATION_TITLES.get(operation, "Add DAG")
    return f"{prefix}[{ticket_id}] {verb} {dag_id}".strip()


def build_pr_body(
    ticket_id: str,
    dag_id: str,
    source: str,
    target: str,
    schedule: str,
    validation: dict,
    operation: str = "CREATE_DAG",
    risk_level: str = "MEDIUM",
    safety_warning: str | None = None,
    ai_generated: bool = False,
    ai_model: str | None = None,
) -> str:
    validation_status = validation.get("overall_status", "UNKNOWN")
    errors = validation.get("errors", [])
    warnings = validation.get("warnings", [])

    errors_text = "\n".join([f"- {error}" for error in errors]) if errors else "- None"
    warnings_text = "\n".join([f"- {warning}" for warning in warnings]) if warnings else "- None"

    # Risk banner for HIGH / CRITICAL ops
    risk_banner = ""
    if risk_level in ("HIGH", "CRITICAL"):
        risk_banner = f"""
> [!WARNING]
> **Risk Level: {risk_level} — REQUIRES MANUAL APPROVAL BEFORE MERGE**
"""

    # Safety warning (DELETE redirect etc.)
    safety_block = ""
    if safety_warning:
        safety_block = f"""
> [!CAUTION]
> {safety_warning}
"""

    # Operation-specific sections
    operation_section = ""
    if operation == "DEPRECATE_DAG":
        operation_section = f"""
## Deprecation Record

| Field | Value |
|---|---|
| DAG ID | `{dag_id}` |
| Ticket | {ticket_id} |
| Action | Deprecate — schedule set to None, deprecated tag added |
"""
    elif operation == "DISABLE_DAG":
        operation_section = f"""
## Disable Rationale

This PR disables `{dag_id}` by setting `schedule=None` and `is_paused_upon_creation=True`.
The DAG will stop scheduling new runs after this change is merged.
"""
    elif operation == "ARCHIVE_DAG":
        operation_section = f"""
## Archive Record

The original DAG file has been copied to `generated_dags/archive/{dag_id}_dag.py`.
The original file has been marked with an ARCHIVED header.
Remove the original file in a follow-up PR after this is approved.
"""

    # AI code review checklist
    ai_checklist = ""
    if ai_generated:
        ai_checklist = f"""
## ⚠️ AI-Generated Code Review Checklist

This DAG was generated by **AWS Bedrock** (`{ai_model or 'unknown model'}`).
All items below must be verified by a human engineer before approving.

- [ ] Correct Airflow operator used for this pipeline type
- [ ] Connection IDs match Airflow environment connections
- [ ] No hardcoded credentials or secrets
- [ ] `on_failure_callback` is properly configured
- [ ] SLA definition is appropriate for this pipeline
- [ ] Task dependency graph is logically correct
- [ ] Test file covers all generated tasks
- [ ] Imports are correct and providers are installed
"""

    return f"""
## Jira Ticket

{ticket_id}
{risk_banner}{safety_block}
## DAG Details

| Field | Value |
|---|---|
| DAG ID | `{dag_id}` |
| Source | `{source}` |
| Target | `{target}` |
| Schedule | `{schedule}` |
| Operation | `{operation}` |
| Risk Level | `{risk_level}` |
{operation_section}
## Validation Result

Overall status: `{validation_status}`

### Errors

{errors_text}

### Warnings

{warnings_text}
{ai_checklist}
## Human Review Checklist

- [ ] DAG name is correct
- [ ] Source path/system is correct
- [ ] Target table/system is correct
- [ ] Schedule is correct
- [ ] Retry policy is acceptable
- [ ] No secrets are hardcoded
- [ ] DAG follows team standards
- [ ] Generated test file is meaningful

## Safety Note

This PR was generated by the AI DAG Ops Assistant. Human review is required before merge.
""".strip()


def _add_pr_label(pr_number: int, label: str) -> None:
    """Apply a label to an existing PR. Best-effort — failures are silently ignored."""
    if not settings.github_owner or not settings.github_repo or not settings.github_token:
        return
    url = f"https://api.github.com/repos/{settings.github_owner}/{settings.github_repo}/issues/{pr_number}/labels"
    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        requests.post(url, headers=headers, json={"labels": [label]}, timeout=15)
    except Exception:
        pass


def create_pull_request(
    ticket_id: str,
    dag_id: str,
    source: str,
    target: str,
    schedule: str,
    branch_name: str,
    validation: dict,
    operation: str = "CREATE_DAG",
    risk_level: str = "MEDIUM",
    safety_warning: str | None = None,
    ai_generated: bool = False,
    ai_model: str | None = None,
) -> dict:
    if not settings.github_token:
        return {
            "success": False,
            "message": "Missing GITHUB_TOKEN in .env",
        }

    if not settings.github_owner or not settings.github_repo:
        return {
            "success": False,
            "message": "Missing GITHUB_OWNER or GITHUB_REPO in .env",
        }

    url = f"https://api.github.com/repos/{settings.github_owner}/{settings.github_repo}/pulls"

    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    # Destructive and AI-generated PRs are always draft — require human review before merge
    _DRAFT_OPERATIONS = {"DEPRECATE_DAG", "DISABLE_DAG", "ARCHIVE_DAG"}
    is_draft = ai_generated or operation in _DRAFT_OPERATIONS

    payload = {
        "title": build_pr_title(ticket_id, dag_id, operation=operation, ai_generated=ai_generated),
        "head": branch_name,
        "base": settings.github_base_branch,
        "body": build_pr_body(
            ticket_id=ticket_id,
            dag_id=dag_id,
            source=source,
            target=target,
            schedule=schedule,
            validation=validation,
            operation=operation,
            risk_level=risk_level,
            safety_warning=safety_warning,
            ai_generated=ai_generated,
            ai_model=ai_model,
        ),
        "draft": is_draft,
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code in [200, 201]:
        data = response.json()
        pr_number = data.get("number")
        # Apply label for AI-generated PRs
        if ai_generated and pr_number:
            _add_pr_label(pr_number, "ai-generated-code")
        return {
            "success": True,
            "pr_number": pr_number,
            "pr_url": data.get("html_url"),
            "title": data.get("title"),
            "draft": is_draft,
        }

    # 422: PR already exists for this branch — look it up and return it
    if response.status_code == 422 and "already exists" in response.text:
        list_url = (
            f"https://api.github.com/repos/{settings.github_owner}/{settings.github_repo}/pulls"
            f"?head={settings.github_owner}:{branch_name}&state=open"
        )
        list_resp = requests.get(list_url, headers=headers)
        if list_resp.status_code == 200:
            prs = list_resp.json()
            if prs:
                existing = prs[0]
                return {
                    "success": True,
                    "pr_number": existing.get("number"),
                    "pr_url": existing.get("html_url"),
                    "title": existing.get("title"),
                    "draft": existing.get("draft", False),
                    "note": "PR already existed — returning existing PR",
                }

    return {
        "success": False,
        "status_code": response.status_code,
        "message": response.text,
    }