import requests
from requests.auth import HTTPBasicAuth

from app.config import settings


def build_adf_paragraph(text: str) -> dict:
    """
    Jira Cloud API v3 expects comments in Atlassian Document Format.
    This helper creates a simple paragraph document.
    """
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [
                    {
                        "type": "text",
                        "text": text,
                    }
                ],
            }
        ],
    }


def add_jira_comment(ticket_id: str, comment_text: str) -> dict:
    if not settings.jira_base_url:
        return {
            "success": False,
            "message": "Missing JIRA_BASE_URL in .env",
        }

    if not settings.jira_email or not settings.jira_api_token:
        return {
            "success": False,
            "message": "Missing JIRA_EMAIL or JIRA_API_TOKEN in .env",
        }

    url = f"{settings.jira_base_url}/rest/api/3/issue/{ticket_id}/comment"

    response = requests.post(
        url,
        auth=HTTPBasicAuth(settings.jira_email, settings.jira_api_token),
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
        json={
            "body": build_adf_paragraph(comment_text),
        },
        timeout=30,
    )

    if response.status_code in [200, 201]:
        data = response.json()
        return {
            "success": True,
            "comment_id": data.get("id"),
            "self": data.get("self"),
        }

    return {
        "success": False,
        "status_code": response.status_code,
        "message": response.text,
    }


def build_dag_ops_comment(
    ticket_id: str,
    generated: dict,
    validation: dict,
    git_result: dict | None,
    github_pr_result: dict | None,
    operation: str = "CREATE_DAG",
    risk_level: str = "MEDIUM",
    safety_warning: str | None = None,
) -> str:
    dag_id = generated.get("dag_id")
    source = generated.get("source")
    target = generated.get("target")
    schedule = generated.get("schedule")
    ai_generated = generated.get("change_type") == "AI_GENERATED"
    ai_model = generated.get("ai_model")

    validation_status = validation.get("overall_status", "UNKNOWN")
    warnings = validation.get("warnings", [])
    errors = validation.get("errors", [])

    branch_name = git_result.get("branch_name") if git_result else None
    pr_url = None
    pr_draft = False
    if github_pr_result and github_pr_result.get("success"):
        pr_url = github_pr_result.get("pr_url")
        pr_draft = github_pr_result.get("draft", False)

    warnings_text = "; ".join(warnings) if warnings else "None"
    errors_text = "; ".join(errors) if errors else "None"
    pr_text = pr_url if pr_url else "PR not created yet or push failed"
    draft_notice = " (DRAFT — do not merge until review complete)" if pr_draft else ""

    # Read-only operations: report format, no PR section
    if operation in ("READ_DAG", "VALIDATE_DAG", "DEBUG_DAG_FAILURE"):
        report_type = {
            "READ_DAG": "DAG Inspection Report",
            "VALIDATE_DAG": "DAG Validation Report",
            "DEBUG_DAG_FAILURE": "DAG Debug Report",
        }[operation]

        lines = [
            f"AI DAG Ops Assistant — {report_type}",
            "",
            f"Ticket: {ticket_id}",
            f"DAG ID: {dag_id}",
            f"Operation: {operation}",
            "",
            f"Validation Status: {validation_status}",
            f"Errors: {errors_text}",
            f"Warnings: {warnings_text}",
        ]

        # For DEBUG, include task metadata if available
        if operation == "DEBUG_DAG_FAILURE":
            task_ids = generated.get("task_ids", [])
            if task_ids:
                lines.append(f"Tasks Found: {', '.join(task_ids)}")
            bedrock_analysis = generated.get("bedrock_analysis")
            if bedrock_analysis:
                lines += ["", "Bedrock Root-Cause Analysis:", bedrock_analysis]
            recommendations = generated.get("recommendations", [])
            if recommendations:
                lines += ["", "Recommendations:"]
                lines += [f"  - {r}" for r in recommendations]

        lines += ["", "No code changes were made. This was a read-only operation."]
        return "\n".join(lines)

    # Destructive operations: include risk callout
    risk_notice = ""
    if risk_level in ("HIGH", "CRITICAL"):
        risk_notice = f"\nRisk Level: {risk_level} — Manual approval required before merge.\n"

    safety_block = ""
    if safety_warning:
        safety_block = f"\nSafety Warning: {safety_warning}\n"

    ai_block = ""
    if ai_generated:
        ai_block = (
            f"\n⚠️ AI-Generated Code\n"
            f"Model: {ai_model or 'unknown'}\n"
            f"This DAG code was generated by AWS Bedrock.\n"
            f"Do NOT merge until a human engineer has reviewed ALL code in the PR.\n"
        )

    return (
        f"AI DAG Ops Assistant processed this ticket.\n"
        f"{risk_notice}"
        f"{safety_block}"
        f"\nTicket: {ticket_id}\n"
        f"Operation: {operation}\n"
        f"DAG ID: {dag_id}\n"
        f"Source: {source}\n"
        f"Target: {target}\n"
        f"Schedule: {schedule}\n\n"
        f"Validation: {validation_status}\n"
        f"Errors: {errors_text}\n"
        f"Warnings: {warnings_text}\n\n"
        f"Git branch: {branch_name}\n"
        f"Pull request: {pr_text}{draft_notice}\n"
        f"{ai_block}\n"
        f"Human review is required before merge or deployment."
    )